/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RacesIndexRouteImport } from './routes/races/index'
import { Route as RacesDateRouteImport } from './routes/races/$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesIndexRoute = RacesIndexRouteImport.update({
  id: '/races/',
  path: '/races/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesDateRoute = RacesDateRouteImport.update({
  id: '/races/$date',
  path: '/races/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/races/$date': typeof RacesDateRoute
  '/races': typeof RacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/races/$date': typeof RacesDateRoute
  '/races': typeof RacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/races/$date': typeof RacesDateRoute
  '/races/': typeof RacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/races/$date' | '/races'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/races/$date' | '/races'
  id: '__root__' | '/' | '/races/$date' | '/races/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RacesDateRoute: typeof RacesDateRoute
  RacesIndexRoute: typeof RacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/': {
      id: '/races/'
      path: '/races'
      fullPath: '/races'
      preLoaderRoute: typeof RacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/$date': {
      id: '/races/$date'
      path: '/races/$date'
      fullPath: '/races/$date'
      preLoaderRoute: typeof RacesDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RacesDateRoute: RacesDateRoute,
  RacesIndexRoute: RacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
